### ISSUE TITLE
exception when changing font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anilFree/seascope#27]
```
What steps will reproduce the problem?
1. Chaning font leads to exception

For more details, please see Debian Bug: 751401
http://bugs.debian.org/751401
```

Original issue reported on code.google.com by `riteshsa...@gmail.com` on 7 Jan 2015 at 4:37

**Comment by rickysarraf** [comment]
For the record, the exception is:

```
PythonArgs: ['Seascope.py']
SourcePackage: seascope
Title: Seascope.py crashed with AttributeError in set_font(): 'NoneType' object has no attribute 'setFont'
Traceback:
 Traceback (most recent call last):
   File "Seascope.py", line 42, in file_preferences_cb
     self.code_ctx_view.change_ev_font(ev_font.toString())
   File "/usr/share/pyshared/seascope/view/CodeContextView.py", line 150, in change_ev_font
     cvp.cv.set_font(self.cv_font)
   File "/usr/share/pyshared/seascope/view/EdView.py", line 76, in set_font
     self.lexer.setFont(self.font,-1)
 AttributeError: 'NoneType' object has no attribute 'setFont'
Uname: Linux 4.8.12+ x86_64
UserGroups: adm audio cdrom dip floppy input netdev plugdev staff sudo systemd-journal uml-net video weston-launch
```

**Comment by rickysarraf** [comment]
Here's a patch to fix the issue.

[bug-751401-save-editor-font-in-config.patch.txt](https://github.com/anilFree/seascope/files/639572/bug-751401-save-editor-font-in-config.patch.txt)
